version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "ecommerce"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/lib:/var/lib/mysql